function makeResize(){if($(".section-img-caption .wide-img img").length){var imageSrc=$(".section-img-caption .wide-img img");}else if($(".promotional-area .promotional-area-img img").length){var imageSrc=$(".promotional-area .promotional-area-img img");}else{var imageSrc=$(".img-area-bg img");}
if($(window).width()<=768&&$(window).width()>480){$(imageSrc).each(function(key,value){$(value).attr('src',$(value).data('tablet'));});}else if($(window).width()<=480){$(imageSrc).each(function(key,value){$(value).attr('src',$(value).data('mobile'));});}else{$(imageSrc).each(function(key,value){$(value).attr('src',$(value).data('default'));});}
if($(window).width()<=768){addClassTruncate();$('.title-for-display').html(function(){return $(this).data('title');});$('.title-for-display-solution').html(function(){return $(this).data('title');});}else{removeClassTruncte();$('.title-for-display').html(function(){if($(this).data('titledisplay').length>0){return $(this).data('titledisplay');}else{return $(this).data('title');}});$('.title-for-display-solution').html(function(){if($(this).data('titledisplay').length>0){return $(this).data('titledisplay');}else{return $(this).data('title');}});}}
function addClassTruncate(){classTag='';if($('.case_study-detail .title-for-display-solution').length>0){classTag='.case_study-detail .title-for-display-solution';}if($('.solutions .title-for-display-solution').length>0){classTag='.solutions .title-for-display-solution';}if($('.top .title-for-display').length>0){classTag='.top .title-for-display';}
$(classTag).each(function(){if($(this).data('title')){if($(classTag).length>0){return classTag=='.top .title-for-display'?$(this).addClass('truncate_80'):$(this).addClass('rows-2');}}});}
function removeClassTruncte(){classTag='';if($('.case_study-detail .title-for-display-solution').length>0){classTag='.case_study-detail .title-for-display-solution';}if($('.solutions .title-for-display-solution').length>0){classTag='.solutions .title-for-display-solution';}if($('.top .title-for-display').length>0){classTag='.top .title-for-display';}
$(classTag).each(function(){if($(this).data('titledisplay')){if($(classTag).length>0){return classTag=='.top .title-for-display'?$(this).removeClass('truncate_80'):$(this).removeClass('rows-2');}}});}
function maxHeightCase(){var maxArray=[];$(".top-case-height").css('height','unset');$(".top-case-height").each(function(){maxArray.push($(this).height());});$(".top-case-height").css('height',Math.max(...maxArray));}
$(".navItem .dropDown .toggleButton .close").click(function(){var a='.navItem';event.preventDefault();for(var b,c=document.querySelectorAll(a),d=0;d<c.length;d++)
b=c[d],b.classList.contains("toggleOpen")&&b.classList.remove("toggleOpen")});$(".toggleClosenBlogList").click(function(){a='filter-module';event.preventDefault();var b=document.getElementById(a);b.classList.contains("toggleClose")?b.classList.remove("toggleClose"):b.classList.add("toggleClose")});function addParameterExtLink(){$('#wrapper').find('a').each(function(){var hrefValue=$(this).attr('href');var currentUrl=$(location).attr('href');var external1="https://www.mhi.com";var external2="http://www.mhi.com";var external3="https://spectra.mhi.com";var external4="http://spectra.mhi.com";var parameter_val="utm_source=ETsite&utm_medium=referral&utm_campaign=";if(hrefValue!=null&&(hrefValue.includes(external1)||hrefValue.includes(external2)||hrefValue.includes(external3)||hrefValue.includes(external4))){$(this).attr('href',function(_,href){var parameter=href.includes('?')?'&'+parameter_val+currentUrl:'?'+parameter_val+currentUrl;if(href.slice(-1)=='/'){return href.replace(/.$/,'')+parameter}else{return href+parameter}});}
if(currentUrl.includes('/redirect')){var hrefUrl=$(location).attr('href').split('#');$("#id-redirection").attr('href',function(_,href){return hrefUrl[1]});if($("#id-redirection").length>0&&hrefUrl[1]){$("#id-redirection").text($("#id-redirection").text().replace('redirect-TITLE',hrefUrl[1]));window.location.replace(hrefUrl[1]);}}});}
function paragraphModal(){var baseUrl=window.location.pathname.split("/").filter(function(path){return path.length>0;});baseUrl.unshift(window.location.origin);baseUrl.push("");baseUrl=baseUrl.join("/");var modalFlag=false,close=$('#modalParagraphCloseButton'),container=$('#modal-paragraph-item');target=$('#modal-paragraph-body');$(window).on('load scroll',function(){const scrollTop=$(window).scrollTop();const scrollMax=$(document).height()-window.innerHeight-$('.paragraph-modal-area').attr('paragraph-height');if(scrollTop>=scrollMax){if(!modalFlag){modalFlag=true;container.add(target).css({'opacity':'1','visibility':'visible'});}}});close.on('click',function(){container.add(target).css({'opacity':'0','visibility':'hidden'});});$(document).on('click',function(e){if(!$(e.target).closest('.modal-paragraph-body').length){container.add(target).css({'opacity':'0','visibility':'hidden'});}});}
$(document).ready(function(){$(window).resize(function(){makeResize();maxHeightCase();toggleDisplay();trimRows();});addTrackingClass();addParameterExtLink();trimRows();makeResize();maxHeightCase();toggleDisplay();footerETLogo();iframeVideo();floatContactBtn();paragraphModal();mobileHeaderClose();if($('#case_study_slider').length){$(window).on("load resize",function(){var winW=$(window).width();var off=$('#new_cont').offset();if(off){var marginL=off.left+'px';var lmarginL=(off.left-((winW-1680)/2))+'px';}
if(1680<=winW){$('#case_study_slider .slide-item:first-child .slide-inner').css('margin-left',lmarginL);}else{$('#case_study_slider .slide-item:first-child .slide-inner').css('margin-left',marginL);}
var eleH=$('#case_study_slider .slick-track').height();});}
var touch='ontouchstart'in document.documentElement||navigator.maxTouchPoints>0||navigator.msMaxTouchPoints>0;if(touch){try{for(var si in document.styleSheets){var styleSheet=document.styleSheets[si];if(!styleSheet.rules)continue;for(var ri=styleSheet.rules.length-1;ri>=0;ri--){if(!styleSheet.rules[ri].selectorText)continue;if(styleSheet.rules[ri].selectorText.match(':hover')){styleSheet.deleteRule(ri);}}}}catch(ex){}}});var pc_only=document.querySelectorAll(".mpc_only"),sp_only=document.querySelectorAll(".msp_only");function toggleDisplay(){var a=window.innerWidth;991<a?(pc_only.forEach(function(a){return a.style.display="block"}),sp_only.forEach(function(a){return a.style.display="none"})):(pc_only.forEach(function(a){return a.style.display="none"}),sp_only.forEach(function(a){return a.style.display="block"}))}
function getStringValue(str,desired_length){var count=0,final_value='',format=/[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/,alphaNumeric=/^[0-9a-zA-Z]+$/
for(let i=0;i<str.length;i++){if(count<desired_length){if(alphaNumeric.test(str[i])||format.test(str[i])){count++
final_value+=str[i]}else{count+=2
final_value+=str[i]}}else{final_value+='...'
break;}}
return final_value}
$(document).ready(function(){$(window).on("load",function(){var truncate_80=$(".truncate_80")
var truncate_310=$(".truncate_310")
if(truncate_80){for(var i=0;i<truncate_80.length;i++){var str=truncate_80[i].innerText
truncate_80[i].innerHTML=getStringValue(str,80)}}
if(truncate_310){for(var i=0;i<truncate_310.length;i++){var str=truncate_310[i].innerText
truncate_310[i].innerHTML=getStringValue(str,310)}}});});$(document).ready(function(){var target=$('#introduction .bg-sticker-area .content-area.bg-white')
if(target){target.fadeIn();setTimeout(function(){target.css('opacity','1');target.css('transform','translateY(0)');},1000);}});function footerETLogo(){var language=document.documentElement.lang;if(language=='ja'){$(".footer-logo a.footer-logo-mhi").attr("href","/jp");}}
function trimRows(){(function($,Drupal){var language=document.documentElement.lang;if($(window).width()>480){$('.spec-rows-2').trunk8();$('.rows-2').trunk8();$('.rows-3').trunk8();$('.rows-4').trunk8();$('.html-rows-3').trunk8();$('.spec-rows-2').trunk8({lines:language=='ja'?2:3});$('.rows-2').trunk8({lines:2});$('.rows-3').trunk8({lines:3});$('.rows-4').trunk8({lines:4});$('.html-rows-3').trunk8({lines:4});}else{if($('.rows-3').length>0){$('.rows-3').trunk8();$('.rows-3').trunk8('revert');}
if($('.spec-rows-2').length>0){$('.spec-rows-2').trunk8();$('.spec-rows-2').trunk8('revert');}
if($('.rows-2').length>0){$('.rows-2').trunk8();$('.rows-2').trunk8('revert');}
if($('.rows-4').length>0){$('.rows-4').trunk8();$('.rows-4').trunk8('revert');}
if($('.html-rows-3').length>0){$('.html-rows-3').trunk8();$('.html-rows-3').trunk8('revert');}}})(jQuery,Drupal)}
function iframeVideo(){var vid_iframe=$('iframe.cta_vid');if(vid_iframe.length>0){for(var i=0;i<vid_iframe.length;i++){var class_v=$(vid_iframe[i]).attr('class');var iframe_src=$(vid_iframe[i]).attr('src');var youtube_video_id=iframe_src.match(/youtube\.com.*(\?v=|\/embed\/)(.{11})/).pop();var nid=class_v.replace('cta_vid p-','');if(youtube_video_id.length==11){var video_thumbnail=$('<div id = "vid-image-sec-'+nid+'" class = "vid-image-sec"><img class = "video-img-'+nid+' imgtracking" src="//img.youtube.com/vi/'+youtube_video_id+'/0.jpg"></div>');$('.thumbnail-'+nid).append(video_thumbnail);}
$('#'+nid+'.video-wrapper').css({'z-index':'unset'});$('#vid-image-sec-'+nid).click(function(){nid=($(this).attr('id')).replace('vid-image-sec-','');targetvid=$('.thumbnail-'+nid+' #vid-src-body');containervid=$('.thumbnail-'+nid+' #vid-src-item-'+nid);close=$('#modalCloseButton-'+nid);containervid.add(targetvid).css({'opacity':'1','visibility':'visible'});containervid.addClass('is-open');close.on('click',function(){class_x=($(this).attr('id')).replace('modalCloseButton-','');$('iframe.cta_vid.p-'+class_x).attr('src',$('iframe.cta_vid.p-'+class_x).attr('src'));containervid.add(targetvid).css({'opacity':'0','visibility':'hidden'});containervid.removeClass('is-open');});$(containervid).click(function(){class_x=($(this).attr('id')).replace('vid-src-item-','');$('iframe.cta_vid.p-'+class_x).attr('src',$('iframe.cta_vid.p-'+class_x).attr('src'));$(this).add(targetvid).css({'opacity':'0','visibility':'hidden'});containervid.removeClass('is-open');});$(targetvid).on('click',function(e){e.stopPropagation();});});}
if($('.p-vid-capt').length>0){$('.p-vid-capt .vid-image-sec').add($('.p-vid-capt .vid-image-sec img')).css({'height':'100%'});}}
var img_src=$('img.img-src-cta');if(img_src.length>0){for(var j=0;j<img_src.length;j++){$(img_src[j]).addClass('imgtracking');var class_i=$(img_src[j]).attr('class');var nid=class_i.replace('img-src-cta p-','');var nid=nid.replace(' imgtracking','');$('img.img-src-cta.p-'+nid+'.imgtracking').click(function(){nid=($(this).attr('class')).replace('img-src-cta p-','');nid=nid.replace(' imgtracking','');targetimg=$('.thumbnail-'+nid+' #image-src-body'),containerimg=$('.thumbnail-'+nid+' #image-src-item');containerimg.add(targetimg).css({'opacity':'1','visibility':'visible'});close=$('#modalCloseButton-'+nid);close.on('click',function(){containerimg.add(targetimg).css({'opacity':'0','visibility':'hidden'});});$(containerimg).click(function(){$(this).add(targetimg).css({'opacity':'0','visibility':'hidden'});});$(targetimg).on('click',function(e){e.stopPropagation();});});}}}
function addTrackingClass(){var aTag=$("#wrapper .dialog-off-canvas-main-canvas a");if(aTag.length>0){aTag.each(function(){$(this).addClass('tracking');})}}
function floatContactBtn(){var float_contact=$('.float_contact_button');if(float_contact.length>0){const windowHeight=$(window).height();const footerPos=$('#footer').offset().top;const scrollVal=footerPos-windowHeight;$(window).on('scroll',function(){const scrollTop=$(window).scrollTop();console.log(scrollTop);if(scrollTop>=scrollVal){float_contact.fadeOut();}else{float_contact.fadeIn();}});}}
function mobileHeaderClose(){var target_item=document.querySelector('.navItem a[href*="#"]');var body_el=document.getElementById('body_el');target_item.addEventListener('click',function(){if(body_el.classList.contains('toggleOpen')){body_el.classList.remove('toggleOpen');}});}